### 1、导入numpy模块，并且给numpy取别名为np

In [47]:
import numpy as np

### 2、随机生成最小值不低于2，最大值不高于10的2行5列数组
**<font color="red">（提示：可通过     np.random.randint?     查看函数说明，思考如何限制2行5列）</font>**

In [48]:
arr = np.random.randint(2,11,size=(2,5))
arr

array([[3, 2, 9, 7, 3],
       [6, 3, 2, 9, 6]], dtype=int32)

### 3、查看下列数组的各项属性（维度，形状，元素个数，类型等）

**<font color="red">关于数组形状,可从外向里看（最外层中包含多少元素项，中间层中每个单元包含多少元素项，最内层每个单元包含多少元素项）</font>**


In [49]:
arr=np.array([[[1,2,3],[4,5,6]],
              [[5,7,8],[7,8,9]],
              [[9,10,11],[12,13,14]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  7,  8],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [50]:
print('数组arr的维度为:',arr.ndim)
print('数组arr的形状为:',arr.shape)
print('数组arr的元素个数为:',arr.size)
print('数组arr的类型为:',arr.dtype)


数组arr的维度为: 3
数组arr的形状为: (3, 2, 3)
数组arr的元素个数为: 18
数组arr的类型为: int64


### 4、创建如下二维数组，尝试运行arr2[1]，arr2[0, 1:4]，arr2[::-1]，arr2[:,::-1]验证其结果

In [51]:
import numpy as np
arr2=np.arange(2,25,2).reshape(3,4)
arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [52]:
print('arr2[1]的结果为:',arr2[1])
print('arr2[0,1:4]的结果为:',arr2[0,1:4])
print('arr2[::-1]的结果为:',arr2[::-1])
print('arr2[:,::-1]的结果为:',arr2[:,::-1])


arr2[1]的结果为: [10 12 14 16]
arr2[0,1:4]的结果为: [4 6 8]
arr2[::-1]的结果为: [[18 20 22 24]
 [10 12 14 16]
 [ 2  4  6  8]]
arr2[:,::-1]的结果为: [[ 8  6  4  2]
 [16 14 12 10]
 [24 22 20 18]]


### 5、接上题：如若想一下获取，(0, 1), (1, 2),(2, 3)这三个元素组成的数组，要如何实现

In [53]:

arr2[[0,1,2],[1,2,3]]

array([ 4, 14, 24])

### 6、筛选数组中大于3且小于10的元素

In [54]:
arr2[(arr2>3) & (arr2<10)]


array([4, 6, 8])

### 7、创建一个由0-13组成的整数数组，形状为2行7列

In [55]:
arr3 = np.arange(0,14).reshape(2,7)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

### 8、尝试利用表达式和函数计算m和n两个数组的加减乘除

In [56]:
m=np.array([[10,20,30],[40,50,60]])
m

array([[10, 20, 30],
       [40, 50, 60]])

In [57]:
n=np.array([[1,2,3],[4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
print('m + n = ',np.add(m,n))
print('m - n = ',np.subtract(m,n))
print('m x n = ',np.multiply(m,n))
print('m / n = ',np.divide(m,n))


m + n =  [[11 22 33]
 [44 55 66]]
m - n =  [[ 9 18 27]
 [36 45 54]]
m x n =  [[ 10  40  90]
 [160 250 360]]
m / n =  [[10. 10. 10.]
 [10. 10. 10.]]


### 9、尝试利用数组n和下面的数组t做点乘
**<font color="red">矩阵计算的前提：第一个矩阵的列数 = 第二个矩阵的行数</font>**

In [59]:
t=np.arange(1,7).reshape(3,2)
print(n.shape)
t.shape

(2, 3)


(3, 2)

In [60]:
print(n)
print(t)
print('n . t = ',np.dot(n,t))


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
n . t =  [[22 28]
 [49 64]]
